# Generated by Django 3.0.7 on 2020-07-25 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('alias', models.CharField(blank=True, help_text='[Optional] use this field to search this form for later', max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='[Optional] custom description', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'form_meta',
            },
        ),
        migrations.CreateModel(
            name='Form_1099',
            fields=[
                ('formmeta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms_v1.FormMeta')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Total income earned in $ amount rounded up to two decimal places', max_digits=19)),
                ('total_business_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Total business expenses in $ amount rounded up to two decimal places', max_digits=19)),
                ('total_miles_driven', models.IntegerField(help_text='Total miles driven rounded to the nearest integer')),
                ('total_taxable_income', models.IntegerField(help_text='Computed', null=True)),
            ],
            options={
                'db_table': 'form_1099',
            },
            bases=('forms_v1.formmeta',),
        ),
        migrations.CreateModel(
            name='Form_W2',
            fields=[
                ('formmeta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms_v1.FormMeta')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Total income earned in $ amount rounded up to two decimal places', max_digits=19)),
                ('total_taxes_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Total taxes paid in $ amount accurate rounded up to two decimal places', max_digits=19)),
                ('total_taxable_income', models.IntegerField(help_text='Computed', null=True)),
            ],
            options={
                'db_table': 'form_W2',
            },
            bases=('forms_v1.formmeta',),
        ),
        migrations.CreateModel(
            name='Tax_Form_1040',
            fields=[
                ('formmeta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms_v1.FormMeta')),
                ('total_taxable_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of taxable incomes across all Form 1099 \u200band Form W-2', max_digits=19, null=True)),
                ('total_taxes_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum tax paid across all Form W-2', max_digits=19, null=True)),
                ('total_tax_liability', models.DecimalField(decimal_places=2, default=0.0, help_text='Computed', max_digits=19, null=True)),
                ('tax_difference', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax paid minus total tax liability', max_digits=19, null=True)),
            ],
            options={
                'db_table': 'tax_form_1040',
            },
            bases=('forms_v1.formmeta',),
        ),
        migrations.AddConstraint(
            model_name='formmeta',
            constraint=models.UniqueConstraint(fields=('alias', 'id'), name='alias and pk'),
        ),
    ]
