# Generated by Django 3.0.7 on 2020-07-25 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='[Unique] Form Name', max_length=100)),
                ('alias', models.CharField(blank=True, help_text='[Optional] use this field to search this form for later', max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='[Optional] custom description', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'form_definition',
            },
        ),
        migrations.CreateModel(
            name='FormFieldDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Field Name', max_length=100)),
                ('reference_name', models.CharField(blank=True, help_text='Field Name', max_length=100, null=True)),
                ('display_order', models.IntegerField(help_text='Display order number')),
                ('data_type', models.CharField(choices=[('integer', 'integer'), ('string', 'string'), ('decimal', 'decimal'), ('enum', 'enum'), ('computed', 'computed')], max_length=20)),
                ('description', models.CharField(blank=True, help_text='[Optional] custom description', max_length=1000, null=True)),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields_definitions', to='forms_v2.FormDefinition')),
            ],
            options={
                'db_table': 'form_field_definition',
            },
        ),
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, help_text='[Optional] custom description', max_length=1000, null=True)),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_v2.FormDefinition')),
            ],
            options={
                'db_table': 'form_instance',
            },
        ),
        migrations.CreateModel(
            name='FormFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(blank=True, help_text='FieldValue', max_length=500, null=True)),
                ('reference_name', models.CharField(blank=True, help_text='Field Name', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='[Optional] custom description', max_length=1000, null=True)),
                ('form_field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_v2.FormFieldDefinition')),
                ('form_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_instance_fields', to='forms_v2.FormInstance')),
            ],
            options={
                'db_table': 'form_field_value',
            },
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(fields=('name',), name='name constraint'),
        ),
        migrations.AddConstraint(
            model_name='formfielddefinition',
            constraint=models.UniqueConstraint(fields=('reference_name', 'id'), name='reference_name and pk'),
        ),
        migrations.AddConstraint(
            model_name='formfielddefinition',
            constraint=models.UniqueConstraint(fields=('display_order', 'form_definition'), name='display_order and form_definition'),
        ),
    ]
